(org-babel-load-file "~/.emacs.d/config/reduce-garbage.org")
(org-babel-load-file "~/.emacs.d/config/better-defaults.org")
(org-babel-load-file "~/.emacs.d/config/programming-modes.org") ;; TODO: Discover which package is messing with this script setup (an install from scratch fails if this is after helpful-packages)
(org-babel-load-file "~/.emacs.d/config/ivy.org")
(org-babel-load-file "~/.emacs.d/config/visuals.org")
(org-babel-load-file "~/.emacs.d/config/functions.org")
(org-babel-load-file "~/.emacs.d/config/helpful-packages.org")
(org-babel-load-file "~/.emacs.d/config/magit.org")
(org-babel-load-file "~/.emacs.d/config/projectile.org")
(org-babel-load-file "~/.emacs.d/config/roam.org")
